// <auto-generated />
using KanaQuiz.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KanaQuiz.Infrastructure.Migrations
{
    [DbContext(typeof(KanaQuizContext))]
    partial class KanaQuizContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("KanaQuiz.Core.Models.Kana", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Romanji")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Kanas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Romanji = "a",
                            Type = 0,
                            Value = "あ"
                        },
                        new
                        {
                            Id = 2L,
                            Romanji = "i",
                            Type = 0,
                            Value = "い"
                        },
                        new
                        {
                            Id = 3L,
                            Romanji = "u",
                            Type = 0,
                            Value = "う"
                        },
                        new
                        {
                            Id = 4L,
                            Romanji = "e",
                            Type = 0,
                            Value = "え"
                        },
                        new
                        {
                            Id = 5L,
                            Romanji = "o",
                            Type = 0,
                            Value = "お"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
