version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    description: Build application
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "src/KanaQuiz.Web.Server/KanaQuiz.Web.Server.csproj" }}
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/KanaQuiz.Web.Server/KanaQuiz.Web.Server.csproj" }}

  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage

workflows:
  test_and_build:
    jobs:
      - build
      - test:
          requires:
            - build